// <auto-generated />
using System;
using BankAccountTransactions.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BankAccountTransactions.Data.Migrations
{
    [DbContext(typeof(BankAccountTransactionsContext))]
    [Migration("20250126105448_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BankAccountTransactions.Domain.Entity.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("accountNumber");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric")
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("createdAt");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("document");

                    b.HasKey("Id");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.ToTable("accounts", "bank");
                });

            modelBuilder.Entity("BankAccountTransactions.Domain.Entity.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("ReceiverDocument")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("receiverDocument");

                    b.Property<string>("SenderDocument")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("senderDocument");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("transactiondate");

                    b.HasKey("Id");

                    b.ToTable("transactions", "bank");
                });

            modelBuilder.Entity("BankAccountTransactions.Domain.Entity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("accountId");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasColumnType("varchar(18)")
                        .HasColumnName("document");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("varchar(2)")
                        .HasColumnName("userType");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Document")
                        .IsUnique()
                        .HasDatabaseName("IX_User_Document");

                    b.ToTable("users", "bank", t =>
                        {
                            t.HasCheckConstraint("CK_users_userType_Enum", "\"userType\" IN ('PF', 'PJ')");
                        });
                });

            modelBuilder.Entity("BankAccountTransactions.Domain.Entity.User", b =>
                {
                    b.HasOne("BankAccountTransactions.Domain.Entity.Account", "Account")
                        .WithOne()
                        .HasForeignKey("BankAccountTransactions.Domain.Entity.User", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
